### ISSUE TITLE
Terraform 0.13 has `id` changing to current clock time every plan/apply on all `data` resources

### ISSUE THREAD

**Issue by ClashTheBunny** [terraform-providers/terraform-provider-oci#1147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
 ❯ terraform -v                                                                                                                             [12:00:37]
Terraform v0.13.0
+ provider registry.terraform.io/-/acme v1.5.0
+ provider registry.terraform.io/-/cloudflare v2.9.0
+ provider registry.terraform.io/-/http v1.2.0
+ provider registry.terraform.io/-/local v1.4.0
+ provider registry.terraform.io/-/oci v3.89.0
+ provider registry.terraform.io/-/template v2.1.2
+ provider registry.terraform.io/-/tls v2.2.0
+ provider registry.terraform.io/hashicorp/http v1.2.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/oci v3.89.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/terraform-providers/acme v1.5.0
+ provider registry.terraform.io/terraform-providers/cloudflare v2.9.0

```

### Affected Resource(s)

Every `data` resource that I use.

### Expected Behavior

Things that are not substantively changing shouldn't pollute the output of a plan or apply.

### Actual Behavior

Pages and pages of data, like every single test image available. On apply, it refreshes those resources:
```
Plan: 0 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.instances.data.oci_core_images.test_images: Reading... [id=2020-08-15 16:52:26.004785768 +0000 UTC]                                            
module.instances.data.oci_core_images.test_images: Read complete after 0s [id=2020-08-15 16:52:39.189842651 +0000 UTC]                                
module.instances.data.oci_core_vnic_attachments.instance_vnics[1]: Reading... [id=2020-08-15 16:52:27.771205613 +0000 UTC]                            
module.instances.data.oci_core_vnic_attachments.instance_vnics[1]: Read complete after 0s [id=2020-08-15 16:52:37.978909454 +0000 UTC]                
module.instances.data.oci_core_vnic_attachments.instance_vnics[0]: Reading... [id=2020-08-15 16:52:27.720728239 +0000 UTC]                            
module.instances.data.oci_core_vnic_attachments.instance_vnics[0]: Read complete after 0s [id=2020-08-15 16:52:38.0660627 +0000 UTC]                  

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. `terraform apply` with 0.13

### Important Factoids

I just went with the default upgrade to terraform 0.13

**Comment by varmax2511** [comment]
Hi @ClashTheBunny -- thanks for reaching out. We are tracking this issue with terraform core: https://github.com/hashicorp/terraform/issues/25812

**Comment by alexng-canuck** [comment]
@ClashTheBunny , this is an issue in the Terraform v0.13.0 CLI which regressed the previous v0.12.X CLI behavior.

The v0.13.1 of the Terraform CLI was released recently and should resolve this issue. Closing the ticket.

https://www.terraform.io/downloads.html

https://github.com/hashicorp/terraform/blob/v0.13.1/CHANGELOG.md

**Comment by gibsonje** [comment]
Terraform v0.13.5 I'm still seeing id change on every apply for AWS datasources.
